AWSTemplateFormatVersion: 2010-09-09
Description: ---
# Metadata: 

# Parameters: 

# Mappings: 

# Conditions: 

Resources:
  myInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-055d15d9cfddf7bd3 
      KeyName: do0803
      InstanceType: t2.micro
      SecurityGroupIds: [!Ref mySG]

  mySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0


# Outputs: