AWSTemplateFormatVersion: 2010-09-09
Description: A nested stack for VPC
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Project Setup'
        Parameters:
          - ProjectName
          - ProjectEnvironment
      
      - Label:
          default: 'Subnet setup'
        Parameters:
          - VPC
          - PrivateCIDR
          - PublicCIDR

    ParameterLabels:
      ProjectName:
        default: 'Project name'
      ProjectEnvironment:
        default: 'Project environment'
      PublicCIDR:
        default: 'Public subnet CIDR'
      PrivateCIDR:
        default: 'Private subnet CIDR'
      VPC:
        label: Choose VPC

Parameters: 
  ProjectName:
    Description: You need to specify a project name for all the stack you are creating.
    Type: String

  ProjectEnvironment:
    Description: You need to specify a name of the environment.
    Type: String

  VPC:
    Description: You need to specify a VPC
    Type: AWS::EC2::VPC::Id

  PrivateCIDR:
    Description: You need to specify an CIDR Block for Private subnet
    Type: String
    AllowedPattern: "([0-9]{1,3})\\.([0-9]{1,3})\\.([0-9]{1,3})\\.([0-9]{1,3})/([0-9]{1,2})"
    Default: "172.1.1.0/24"

  PublicCIDR:
    Description: You need to specify an CIDR Block for Public subnet
    Type: String
    AllowedPattern: "([0-9]{1,3})\\.([0-9]{1,3})\\.([0-9]{1,3})\\.([0-9]{1,3})/([0-9]{1,2})"
    Default: "172.1.2.0/24"


# Mappings: 

# Conditions: 

Resources: 
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: ""
      CidrBlock: !Ref PublicCIDR
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags: 
        - Key: Name
          Value: !Join ["-", [!Ref ProjectName, !Ref ProjectEnvironment]] 
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref ProjectEnvironment

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: ""
      CidrBlock: !Ref PrivateCIDR
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags: 
        - Key: Name
          Value: !Join ["-", [!Ref ProjectName, !Ref ProjectEnvironment]]
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref ProjectEnvironment

Outputs:
  PublicSubnetId:
    Description: Public subnet Id created
    Value: !Ref PublicSubnet
    Export:
      Name: !Sub '${AWS::StackName}-PublicSubnetId'

  PrivateSubnetId:
    Description: Public subnet Id created
    Value: !Ref PrivateSubnet
    Export:
      Name: !Sub '${AWS::StackName}-PrivateSubnetId'

