AWSTemplateFormatVersion: 2010-09-09
Description: A nested stack for VPC
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Project Setup'
        Parameters:
          - ProjectName
          - ProjectEnvironment
      
      - Label:
          default: 'Subnet setup'
        Parameters:
          - VPC
          - PrivateCIDR
          - PublicCIDR

    ParameterLabels:
      ProjectName:
        default: 'Project name'
      ProjectEnvironment:
        default: 'Project environment'
      PublicCIDR:
        default: '172.1.0.0/24'
      PrivateCIDR:
        default: '172.1.1.0/24'
      VPC:
        label: Choose VPC

Parameters: 
  ProjectName:
    Description: You need to specify a project name for all the stack you are creating.
    Type: String

  ProjectEnvironment:
    Description: You need to specify a name of the environment.
    Type: String

  VPC:
    Description: You need to specify an VPC CIDR Block like 172.1.0.0/16
    Type: AWS::EC2::VPC::Id




# Mappings: 

# Conditions: 

Resources: 
  publicSubnet:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VpcCIDRBlock

      Tags: 
        - Key: Name
          Value: !Join ["-", [!Ref ProjectName, !Ref ProjectEnvironment]] 

  privateSubnet:
    Type: 
    Properties:
      
      Tags: 
        - Key: Name
          Value: !Join ["-", [!Ref ProjectName, !Ref ProjectEnvironment]] 

Outputs:
  PublicSubnetId:
    Description: Public subnet Id created
    Value: !Ref customVPC

  DefaultNetworkAcl:
    Description: Default Network Acl
    Value: !GetAtt [customVPC,DefaultNetworkAcl]

  DefaultSecurityGroup:
    Description: Default Security Group
    Value: !GetAtt [customVPC,DefaultSecurityGroup]
