AWSTemplateFormatVersion: 2010-09-09
Description: A nested stack for VPC
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Project Setup'
        Parameters:
          - ProjectName
          - ProjectEnvironment
      
      - Label:
          default: 'VPC configuration'
        Parameters:
          - VpcCIDRBlock

    ParameterLabels:
      ProjectName:
        default: 'Project name'
      ProjectEnvironment:
        default: 'Project environment'
      VpcCIDRBlock:
        default: 'Type of EC2 Instance'
      IncludeIGW:
        default: 'Include Internet Gateway'

Parameters: 
  ProjectName:
    Description: You need to specify a project name for all the stack you are creating.
    Type: String

  ProjectEnvironment:
    Description: You need to specify a name of the environment.
    Type: String

  VpcCIDRBlock:
    Description: You need to specify an VPC CIDR Block like 172.1.0.0/16
    Type: String
    AllowedPattern: "([0-9]{1,3})\\.([0-9]{1,3})\\.([0-9]{1,3})\\.([0-9]{1,3})/([0-9]{1,2})"
    Default: "172.1.0.0/16"

  IncludeIGW:
    Description: If this VPC include Internet GW or not.
    Type: String
    AllowedValues: [true, false]
    Default: true


# Mappings: 

Conditions: 
  HasIGW: !Equals [!Ref IncludeIGW, true]

Resources: 
  customVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VpcCIDRBlock
      EnableDnsHostnames: false
      EnableDnsSupport: false
      InstanceTenancy: default
      # Ipv4IpamPoolId: String
      # Ipv4NetmaskLength: Integer
      Tags: 
        - Key: Name
          Value: !Join ["-", [!Ref ProjectName, !Ref ProjectEnvironment]] 

  IGW:
    Type: AWS::EC2::InternetGateway
    Condition: HasIGW
    Properties:
      Tags: 
        - Key: Name
          Value: !Join ["-", [!Ref ProjectName, !Ref ProjectEnvironment]] 

  AttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Condition: HasIGW
    Properties:
      VpcId: !Ref customVPC
      InternetGatewayId: !Ref IGW

Outputs:
  VPCId:
    Description: VPC Id created
    Value: !Ref customVPC

  DefaultNetworkAcl:
    Description: Default Network Acl
    Value: !GetAtt [customVPC, DefaultNetworkAcl]

  DefaultSecurityGroup:
    Description: Default Security Group
    Value: !GetAtt [customVPC, DefaultSecurityGroup]

  IGWId:
    Condition: HasIGW
    Description: Internet GW Id
    Value: !GetAtt [IGW, InternetGatewayId]
