AWSTemplateFormatVersion: 2010-09-09
Description: ---
# Metadata: 

# Parameters: 

# Mappings: 

# Conditions: 

Resources: 
  myStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://cf-templates-1egp1niusfxri-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/subnet.yaml
      Parameters: 
        projectName : projectUsingStack
        env: stag



Outputs:
  publicSubnetVPCId:
    Value: !GetAtt myStack.Outputs.publicSubnetVPCId